In [4]:
#importing the libraries
import numpy as np
import pandas as pd

In [5]:
#uploading dataet
data=pd.read_csv('IMDB Dataset.csv')

In [6]:
#sample
data.sample(10)

review sentiment
34852  I think "Rosemary's Baby" is the most overrate...  negative
12133  Three story lines and not enough tying them to...  negative
132    "The Danish Bladerunner" is boldly stated on t...  negative
43790  My expectations were quite high for this film....  positive
22186  I saw this in a sneak two days before the offi...  negative
592    As is often the case when you attempt to take ...  positive
11703  Even though it has one of the standard "Reveng...  positive
14745  The Lion King series is easily the crowning ac...  positive
32791  We also found this movie on the discount rack ...  negative
18893  Unless you are already familiar with the pop s...  negative

In [7]:
df=data.iloc[:10000]

In [8]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [9]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [10]:
df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [11]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [12]:
df.duplicated().sum()

17

In [13]:
df.drop_duplicates(inplace=True)

<ipython-input-13-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [14]:
#Basic preprocessing
#Remove tags
#Lower case
#remove stopwords

In [15]:
import re
def remove_tags(raw_text):
    cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
    return cleaned_text

In [16]:
df['review']=df['review'].apply(remove_tags)

<ipython-input-16-16f7647403ce>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)


In [17]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [18]:
df['review']=df['review'].apply(lambda x:x.lower())

<ipython-input-18-abab709f0c77>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())


In [19]:
 import nltk
 nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
import nltk
from nltk.corpus import stopwords

# Download the stopwords list if you haven't already
nltk.download('stopwords')

# Assuming df is your DataFrame and 'review' is the column with text
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: ' '.join([item for item in x.split() if item not in sw_list]))


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
<ipython-input-20-77f8467be8b7>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: ' '.join([item for item in x.split() if item not in sw_list]))


In [21]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [22]:
x=df.iloc[:,0:1]
y=df['sentiment']

In [23]:
x

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [24]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [27]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [28]:
  from sklearn.model_selection import train_test_split
  x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [29]:
x_train.shape

(7986, 1)

In [30]:
#Applying bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [31]:
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()

In [32]:
x_train_bow.shape

(7986, 48282)

In [33]:
#Naive BAYES
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()

In [34]:
gb.fit(x_train_bow,y_train)

GaussianNB()

In [35]:
y_pred=gb.predict(x_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [36]:
print(confusion_matrix(y_test,y_pred))

[[717 235]
 [499 546]]


In [37]:
#Randomforestclassifier
from sklearn.ensemble import RandomForestClassifier
RFC=RandomForestClassifier()

In [38]:
RFC.fit(x_train_bow,y_train)
y_pred=RFC.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.8397596394591887

In [39]:
y_pred=RFC.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.8397596394591887

In [40]:
print(confusion_matrix(y_test,y_pred))

[[801 151]
 [169 876]]


In [41]:
cv=CountVectorizer(max_features=3000)
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()
rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred=rf.predict(x_test_bow)
print(confusion_matrix(y_test,y_pred))


[[804 148]
 [168 877]]


In [42]:
accuracy_score(y_test,y_pred)

0.8417626439659489

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(ngram_range=(1,3),max_features=5000)
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()
rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred=rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.8397596394591887

TF- **IDF**

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfv=TfidfVectorizer()
x_train_tfidf=tfv.fit_transform(x_train['review']).toarray()
x_test_tfidf=tfv.transform(x_test['review']).toarray()
rf=RandomForestClassifier()
rf.fit(x_train_tfidf,y_train)
y_pred=rf.predict(x_test_tfidf)
accuracy_score(y_test,y_pred)


0.842764146219329